<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class tuittyTuittyBundleDocumentPhotoHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['userId'])) {
            $value = $data['userId'];
            $return = (string) $value;
            $this->class->reflFields['userId']->setValue($document, $return);
            $hydratedData['userId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['tuittyId'])) {
            $value = $data['tuittyId'];
            $return = (string) $value;
            $this->class->reflFields['tuittyId']->setValue($document, $return);
            $hydratedData['tuittyId'] = $return;
        }

        /** @Field(type="date") */
        if (isset($data['registrationDate'])) {
            $value = $data['registrationDate'];
            if ($value instanceof \MongoDate) { $return = new \DateTime(); $return->setTimestamp($value->sec); } elseif (is_numeric($value)) { $return = new \DateTime(); $return->setTimestamp($value); } else { $return = new \DateTime($value); }
            $this->class->reflFields['registrationDate']->setValue($document, clone $return);
            $hydratedData['registrationDate'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['path'])) {
            $value = $data['path'];
            $return = (string) $value;
            $this->class->reflFields['path']->setValue($document, $return);
            $hydratedData['path'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['extension'])) {
            $value = $data['extension'];
            $return = (string) $value;
            $this->class->reflFields['extension']->setValue($document, $return);
            $hydratedData['extension'] = $return;
        }

        /** @Field(type="boolean") */
        if (isset($data['active'])) {
            $value = $data['active'];
            $return = (bool) $value;
            $this->class->reflFields['active']->setValue($document, $return);
            $hydratedData['active'] = $return;
        }
        return $hydratedData;
    }
}