<?php

namespace tuitty\TuittyBundle\Repository;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends DocumentRepository
{
    /**
     * Devuelve los comentarios del usuario en cuestión y de todos sus amigos
     * @param type $id (id del usuario)
     * @param type $desc (ordenación: ASC/DESC)
     */
    public function getAllComments($id, $order) {
        return $this->createQueryBuilder()
                ->field('id')->equals($id)
                ->limit(10)
                ->sort('registrationDate', $order)
                ->getQuery()
                ->execute();
    }
}